# Basic deployment
replicaCount: 1

# Enable built-in PostgreSQL
postgresql:
  enabled: true
  auth:
    username: outline
    password: strongpassword
    database: outline
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Enable built-in Redis
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi

# Local file storage
fileStorage:
  mode: local
  local:
    persistence:
      enabled: true
      size: 8Gi

# Ingress for external access
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: rieluwiki.uniproject.jp
      paths:
        - path: /
          pathType: ImplementationSpecific
# Auth settings
auth:
  github:
    enabled: true
    clientId: "Ov23li73x3dDja3595ZH"
    clientSecret: "43dd803badecd24a0e8a96e189c59d55e24c92f2"
# SMTP settings
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "namekotoyuki100@gmail.com"
  password: "jabu osce ebzg ttkz"
  fromEmail: "outline@uniproject.jp"
  replyEmail: "no-reply@uniproject.jp"
  secure: true
